kind: pipeline
type: kubernetes
name: default

steps:
- name: install
  image: oven/bun:1
  commands:
  - bun install

- name: test
  image: oven/bun:1
  commands:
  - bun test

- name: linting
  image: oven/bun:1
  commands:
  - bun lint
  - bun format

- name: build
  image: oven/bun:1
  commands:
  - bun build
